# Ativar ZMK Studio
CONFIG_ZMK_STUDIO=y

# Aumentar compatibilidade com Windows/Chrome
CONFIG_BT_GATT_ENFORCE_SUBSCRIPTION=n
CONFIG_ZMK_BLE_EXPERIMENTAL_CONN=y

# Desativar segurança temporariamente para teste (não precisa de tecla unlock)
CONFIG_ZMK_STUDIO_LOCKING=n

# Ligar o modo de teclado dividido (Split)
CONFIG_ZMK_SPLIT=y
